routes/admin.php
<?php

Route::get('/', 'AdminController@index')->name('index');
Route::resource('users', 'UserController');
Route::resource('templates', 'TemplateController');
Route::resource('settings', 'SettingController');
Route::resource('reports', 'ReportController');
Route::as('reports.')->prefix('reports')->group(function () {
    Route::post('/get-answers', 'ReportController@getAnswers')->name('get-answers');   
}); 

routes/dashboard.php
<?php

Route::get('/', 'DashboardController@index')->name('index');
Route::resource('reports', 'ReportController');

routes/frontend.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/reports', 'ReportController@index')->name('reports.index');
Route::get('/json-reports', 'ReportController@jsonReports')->name('reports.json-reports');

Route::get('/lang/{locale?}', [
    'as'=>'lang',
    'uses'=>'FrontendController@changeLang'
]);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::redirect('/', '/home');
    
    Route::get('/home', 'HomeController@index')->name('home');
});

resources/views/admin/templates/_form.blade.php
{{ Form::model($template, ['route' => !empty($template->id)? ['admin.templates.update', $template->id] : ['admin.templates.store'], 'class' => 'form-horizontal form-label-left', 'id' => 'templates-form', 'enctype' => 'multipart/form-data']) }}
        @method(!empty($template->id)? 'PUT' : 'POST')
        @if (!empty($template->id))
            {{ Form::hidden('id', $template->id) }}
        @endif

        <div class="row form-group">
            <div class="col col-md-3">
                {{ Form::label('input_name', _i('Name'), ['class' => 'form-control-label']) }}
            </div>
            <div class="col-12 col-md-9">
                {{ Form::text("name", $template->name, ["class" => "form-control", "placeholder" => _i('Name'), "id"=>"input_name", 'required' => 'required']) }}
            </div>
        </div>

        <div class="row form-group">
            <div class="col col-md-3">
                {{ Form::label('input_color', _i('Color'), ['class' => 'form-control-label']) }}
            </div>
            <div class="col-12 col-md-9">
                {{ Form::text("color", $template->color, ["class" => "form-control", "placeholder" => _i('Color'), "id"=>"input_color"]) }}
            </div>
        </div>


        <hr/>
        <h3 class="margin-bottom-1">{{ _i('Questions') }}:</h3>
        <div class="form-group">
            <button class="btn btn-warning" @click="addNewQuestion">{{ _i('Add question') }} <i class="fas fa-plus-circle"></i></button>
        </div>
        <div id="questions-block">
            <template-question
                v-for="(question, index) in questions"
                v-bind:key="index"
                v-bind:answer_types="answerTypes"
                v-bind:type_select="typeSelect"
                v-bind:number="index"
                v-bind:question="question"
                v-bind:translations="translations"
                v-on:remove="questions.splice(index, 1)"
            >
            </template-question>
        </div>

        <div class="form-group">
            <div class="float-right">
                {{ Form::submit( !empty($template->id) ? _i('Edit') : _i('Save'), ['class' => 'btn btn-success']) }}
            </div>
            <div class="">
                <a href="{{ route('admin.templates.index') }}" class="btn btn-danger">{{ _i('Cancel') }}</a>
            </div>
        </div>
{{ Form::close() }}

@push('scripts')
    <script>
        var questions = {!! $template->questions->toJson() !!};
        var answerTypes = {!! json_encode($answerTypes) !!};
        var typeSelect =  {!! json_encode($typeSelect) !!};
        var translations = {
                question: '{{ _i("Question") }}',
                hint: '{{ _i("Hint") }}',
                requiredField: '{{ _i("Required field") }}',
                answerType: '{{ _i("Answer type") }}',
                chooseAnswerType: '{{ _i("Choose answer type") }}',
                answerVariants: '{{ _i("Answer variants") }}',
                typeAnswerVariants: '{{ _i("Type your answer and press Enter") }}',
                answerTypes: {
                    text: '{{ _i("text") }}',
                    boolean: '{{ _i("boolean") }}',
                    date: '{{ _i("date") }}',
                    number: '{{ _i("number") }}',
                    select: '{{ _i("select") }}',
                    multiselect: '{{ _i("multiselect") }}',
                },
            };

        window.jQuery(function () {
            window.jQuery('#input_color').colorpicker();
        });
    </script>
    <script src="/js/admin/templates.js" ></script>
@endpush

resources/views/admin/templates/create.blade.php
@extends('layouts.admin')

@section('breadcrumbs', Breadcrumbs::render('admin-templates-create') )

@push('styles')
    <link href="{{ asset('css/admin/bootstrap-colorpicker.min.css') }}" rel="stylesheet">
@endpush

@section('content')
<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="card">
            <div class="card-header">
                <strong>{{ _i('Create template') }}</strong>
            </div>
            <div id="template-block" class="card-body card-block">
                 @include('admin.templates._form')
            </div>
        </div>
    </div><!-- .animated -->
</div><!-- .content -->
@endsection


@push('scripts')
    <script src="/js/admin/bootstrap-colorpicker.min.js" ></script>
@endpush

resources/views/admin/templates/edit.blade.php
@extends('layouts.admin')

@section('breadcrumbs', Breadcrumbs::render('admin-templates-edit', $template) )

@push('styles')
    <link href="{{ asset('css/admin/bootstrap-colorpicker.min.css') }}" rel="stylesheet">
@endpush

@section('content')
<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="card">
            <div class="card-header">
                <strong>{{ _i('Edit template') }}</strong>
            </div>
            <div id="template-block" class="card-body card-block">
                 @include('admin.templates._form')
            </div>
        </div>
    </div><!-- .animated -->
</div><!-- .content -->
@endsection


@push('scripts')
    <script src="/js/admin/bootstrap-colorpicker.min.js" ></script>
@endpush

resources/views/admin/templates/index.blade.php
@extends('layouts.admin')

@section('breadcrumbs', Breadcrumbs::render('admin-templates') )

@push('styles')
@endpush

@section('content')
<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row"> 
            <div class="col-md-12 margin-bottom-1">
                <a href="{{ route('admin.templates.create') }}" class="btn btn-success float-right">{{ _i('Add') }}</a>  
            </div>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title"></strong>
                    </div>
                    <div class="card-body">
                        <table class="data-table-custom table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>{{ _i('Name') }}</th>
                                    <th>{{ _i('Actions') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($templates as $template)                                      
                                    <tr>
                                        <td>{{ $template->name }}</td>
                                        <td>
                                            <a href="{{ route('admin.templates.edit', $template->id) }}" class="btn btn-warning">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            
                                            
                                            <a href="#" onclick="event.preventDefault();document.getElementById('destroy_templates_form_{{ $template->id }}').submit();" class="btn btn-danger">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                            {{Form::open(['id'=>'destroy_templates_form_'.$template->id, 'method'  => 'DELETE', 'route' => ['admin.templates.destroy', $template->id], 'class'=>"delete-form"])}}
                                            {{ Form::close() }}  
                                        </td>
                                    </tr>                                      
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>                 
            </div>
        </div> 
    </div><!-- .animated -->
</div><!-- .content -->
@endsection


@push('scripts')
<script>
    (function ($) {
        $('.data-table-custom').DataTable({
            lengthMenu: [[10, 20, 50, -1], [10, 20, 50, "All"]],
        });
    })(jQuery);   
</script>
@endpush