routes/admin.php
<?php

Route::get('/', 'AdminController@index')->name('index');
Route::resource('users', 'UserController');
Route::resource('templates', 'TemplateController');
Route::resource('settings', 'SettingController');
Route::resource('reports', 'ReportController');
Route::as('reports.')->prefix('reports')->group(function () {
    Route::post('/get-answers', 'ReportController@getAnswers')->name('get-answers');   
}); 

routes/dashboard.php
<?php

Route::get('/', 'DashboardController@index')->name('index');
Route::resource('reports', 'ReportController');

routes/frontend.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/reports', 'ReportController@index')->name('reports.index');
Route::get('/json-reports', 'ReportController@jsonReports')->name('reports.json-reports');

Route::get('/lang/{locale?}', [
    'as'=>'lang',
    'uses'=>'FrontendController@changeLang'
]);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::redirect('/', '/home');
    
    Route::get('/home', 'HomeController@index')->name('home');
});

resources/views/includes/_admin_menu.blade.php
<div id="main-menu" class="main-menu collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li>
            <a href="{{ route('admin.index') }}"> <i class="menu-icon fa fa-home"></i> {{ _i('Home') }} </a>
        </li>
        <li>
            <a href="{{ route('admin.users.index') }}"> <i class="menu-icon fa fa-users"></i> {{ _i('Users') }} </a>
        </li>
        <li>
            <a href="{{ route('admin.templates.index') }}"> <i class="menu-icon fab fa-wpforms"></i> {{ _i('Templates') }} </a>
        </li>
        <li>
            <a href="{{ route('admin.reports.index') }}"> <i class="menu-icon fas fa-file-alt"></i> {{ _i('Reports') }} </a>
        </li>

        <h3 class="menu-title"></h3><!-- /.menu-title -->        
        <li>
            <a href="{{ route('admin.settings.index') }}"> <i class="menu-icon fa fa-tasks"></i>{{ _i('Settings') }} </a>
        </li>
    </ul>
</div><!-- /.navbar-collapse -->

resources/views/includes/_breadcrumbs.blade.php
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                @auth
                <h1>{{ \Laratrust::hasRole('admin') ? _i('Admin dashboard') : _i('Employee dashboard') }}</h1>
                @endauth                
            </div>
        </div>
    </div>
    
    @if (count($breadcrumbs))

    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                @foreach ($breadcrumbs as $breadcrumb)

                    @if ($breadcrumb->url && !$loop->last)
                        <li><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
                    @else
                        <li class="active">{{ $breadcrumb->title }}</li>
                    @endif

                @endforeach
                </ol>
            </div>
        </div>
    </div>

    @endif
</div>

resources/views/includes/_dashboard_menu.blade.php
<div id="main-menu" class="main-menu collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li>
            <a href="{{ route('dashboard.index') }}"> <i class="menu-icon fa fa-home"></i> {{ _i('Home') }} </a>
        </li>
        <li>
            <a href="{{ route('dashboard.reports.index') }}"> <i class="menu-icon fas fa-file-alt"></i> {{ _i('Reports') }} </a>
        </li>
    </ul>
</div><!-- /.navbar-collapse -->

resources/views/includes/_flash_messages.blade.php
<div class="messages" id="row-mesages">

    @if ($errors->any())
        <div class="alert alert-danger">
            <i class="icon icon-flash_danger"></i>
            @foreach ($errors->all() as $error)
                {!! $error !!}<br/>
            @endforeach
        </div>
    @elseif (session()->get('flash_success'))
        <div class="alert alert-success">
            <i class="icon icon-flash_success"></i>
            @if(is_array(json_decode(session()->get('flash_success'), true)))
                {!! implode('', session()->get('flash_success')->all(':message<br/>')) !!}
            @else
                {!! session()->get('flash_success') !!}
            @endif
        </div>
    @elseif (session()->get('flash_warning'))
        <div class="alert alert-warning">
            <i class="icon icon-flash_warning"></i>
            @if(is_array(json_decode(session()->get('flash_warning'), true)))
                {!! implode('', session()->get('flash_warning')->all(':message<br/>')) !!}
            @else
                {!! session()->get('flash_warning') !!}
            @endif
        </div>
    @elseif (session()->get('flash_info'))
        <div class="alert alert-info">
            <i class="icon icon-flash_info"></i>
            @if(is_array(json_decode(session()->get('flash_info'), true)))
                {!! implode('', session()->get('flash_info')->all(':message<br/>')) !!}
            @else
                {!! session()->get('flash_info') !!}
            @endif
        </div>
    @elseif (session()->get('flash_danger'))
        <div class="alert alert-danger">
            <i class="icon icon-flash_danger"></i>
            @if(is_array(json_decode(session()->get('flash_danger'), true)))
                {!! implode('', session()->get('flash_danger')->all(':message<br/>')) !!}
            @else
                {!! session()->get('flash_danger') !!}
            @endif
        </div>
    @elseif (session()->get('flash_message'))
        <div class="alert alert-info">
            <i class="icon icon-flash_info"></i>
            @if(is_array(json_decode(session()->get('flash_message'), true)))
                {!! implode('', session()->get('flash_message')->all(':message<br/>')) !!}
            @else
                {!! session()->get('flash_message') !!}
            @endif
        </div>
    @endif
</div>

resources/views/includes/_header.blade.php
<header id="header" class="header">

    <div class="header-menu">

        @include('includes._menu_toggle')

        <div class="col-sm-5">
            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">     
                    {{--               
                    <!-- <img class="user-avatar rounded-circle" src="images/admin.jpg" alt="User Avatar"> -->
                    --}}
                    <span class="user-avatar rounded-circle">{{ Auth::user()->name }}</span>
                </a>

                <div class="user-menu dropdown-menu">
                    <a onclick="event.preventDefault();
                                  document.getElementById('logout-form').submit();" class="nav-link" href="#"><i class="fa fa-power-off"></i> {{ _i('Log out') }}</a>
                </div>
                
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
            
            <div class="language-select dropdown" id="language-select">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown"  id="language" aria-haspopup="true" aria-expanded="true">
                    <i class="flag-icon flag-icon-{{ \LaravelGettextHelper::getLocaleCountry() }}"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="language">
                    @foreach(Config::get('laravel-gettext.all-locales-languages') as $locale => $lang)
                          <div class="dropdown-item">
                              <a href="/lang/{{$locale}}">
                                  <span class="flag-icon flag-icon-{{ $lang }}"></span>
                              </a>                              
                          </div>                          
                    @endforeach                    
                    <!-- <div class="dropdown-item">
                        <span class="flag-icon flag-icon-fr"></span>
                    </div>
                    <div class="dropdown-item">
                        <i class="flag-icon flag-icon-es"></i>
                    </div>
                    <div class="dropdown-item">
                        <i class="flag-icon flag-icon-us"></i>
                    </div>
                    <div class="dropdown-item">
                        <i class="flag-icon flag-icon-it"></i>
                    </div> -->
                </div>
            </div>
            
        </div>
    </div>

</header><!-- /header -->

resources/views/includes/_menu_toggle.blade.php
<div class="col-sm-7">
    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
    {{--
    <!-- <div class="header-left">
        <button class="search-trigger"><i class="fa fa-search"></i></button>
        <div class="form-inline">
            <form class="search-form">
                <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
            </form>
        </div>

        <div class="dropdown for-notification">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bell"></i>
                <span class="count bg-danger">5</span>
            </button>
            <div class="dropdown-menu" aria-labelledby="notification">
                <p class="red">You have 3 Notification</p>
                <a class="dropdown-item media bg-flat-color-1" href="#">
                <i class="fa fa-check"></i>
                <p>Server #1 overloaded.</p>
            </a>
                <a class="dropdown-item media bg-flat-color-4" href="#">
                <i class="fa fa-info"></i>
                <p>Server #2 overloaded.</p>
            </a>
                <a class="dropdown-item media bg-flat-color-5" href="#">
                <i class="fa fa-warning"></i>
                <p>Server #3 overloaded.</p>
            </a>
            </div>
        </div>

        <div class="dropdown for-message">
            <button class="btn btn-secondary dropdown-toggle" type="button"
                id="message"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="ti-email"></i>
                <span class="count bg-primary">9</span>
            </button>
            <div class="dropdown-menu" aria-labelledby="message">
                <p class="red">You have 4 Mails</p>
                <a class="dropdown-item media bg-flat-color-1" href="#">
                <span class="photo media-left"><img alt="avatar" src="images/avatar/1.jpg"></span>
                <span class="message media-body">
                    <span class="name float-left">Jonathan Smith</span>
                    <span class="time float-right">Just now</span>
                        <p>Hello, this is an example msg</p>
                </span>
            </a>
                <a class="dropdown-item media bg-flat-color-4" href="#">
                <span class="photo media-left"><img alt="avatar" src="images/avatar/2.jpg"></span>
                <span class="message media-body">
                    <span class="name float-left">Jack Sanders</span>
                    <span class="time float-right">5 minutes ago</span>
                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                </span>
            </a>
                <a class="dropdown-item media bg-flat-color-5" href="#">
                <span class="photo media-left"><img alt="avatar" src="images/avatar/3.jpg"></span>
                <span class="message media-body">
                    <span class="name float-left">Cheryl Wheeler</span>
                    <span class="time float-right">10 minutes ago</span>
                        <p>Hello, this is an example msg</p>
                </span>
            </a>
                <a class="dropdown-item media bg-flat-color-3" href="#">
                <span class="photo media-left"><img alt="avatar" src="images/avatar/4.jpg"></span>
                <span class="message media-body">
                    <span class="name float-left">Rachel Santos</span>
                    <span class="time float-right">15 minutes ago</span>
                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                </span>
            </a>
            </div>
        </div>
    </div> -->
    --}}
</div>